services:
  agent-chat-ui:
    image: zukizuk/clock-it
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    container_name: agent-chat-ui

networks:
  default:
    name: clockit-network
